title: Affective Computing Group
description: Vanderbilt University
baseurl: "/affective-computing"
url: "https://affective-computing-vu.github.io"

lab:
  name: Affective Computing Group
  pi: Jonathan Gratch
  university: Vanderbilt University
  college: College of Connected Computing
  email: jonathan.gratch@vanderbilt.edu
  location: Nashville, TN

plugins:
  - jekyll-feed
